### model
model_name_or_path: /data00/models/Qwen/Qwen3-30B-A3B-Instruct-2507
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: my_dataset
template: qwen2
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: saves/qwen3/lora/sft
logging_steps: 10
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: swanlab  # <-- 就是这一行，从 none/tensorboard 改成 swanlab

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
num_train_epochs: 3.0

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500