{
 "title": "Enova-Serve-Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_calls_total{span_name=\"POST /generate\", http_status_code=~\"2..\"}[1m])) / sum by (time) (increase(traces_spanmetrics_calls_total{span_name=\"POST /generate\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_calls_total{span_name=\"POST /generate\", http_status_code=~\"2..\"}[1m])) / sum by (time) (increase(traces_spanmetrics_calls_total{span_name=\"POST /generate\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_calls_total{span_name=\"POST /generate\", http_status_code=~\"2..\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_calls_total{span_name=\"POST /generate\", http_status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "4xx|5xx"
    }
   ]
  },
  {
   "title": "Success Request Duration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_latency_sum{span_name=\"POST /generate\",  http_status_code=~\"2..\"}[1m])) / sum by (time) (increase(traces_spanmetrics_latency_count{span_name=\"POST /generate\"}[1m]))",
     "legendFormat": "2xx"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Size Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_bytes_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_latency_sum{span_name=\"POST /generate\",  http_status_code=~\"2..\"}[1m])) / sum by (time) (increase(traces_spanmetrics_latency_count{span_name=\"POST /generate\", http_status_code=~\"2..\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (time) (increase(traces_spanmetrics_latency_sum{span_name=\"POST /generate\",  http_status_code=~\"2..\"}[1m])) / sum by (time) (increase(traces_spanmetrics_latency_count{span_name=\"POST /generate\", http_status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "4xx|5xx"
    }
   ]
  },
  {
   "title": "Request Size Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_size_bytes_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activate Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_request_size_bytes_sum[1m])) / avg(rate(http_server_request_size_bytes_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_response_size_bytes_sum[1m])) / avg(rate(http_server_response_size_bytes_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}