{
 "title": "Enova-DCGM-Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_DEC_UTIL,instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_DEC_UTIL,gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DCGM_FI_DEV_GPU_UTIL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DCGM_FI_DEV_MEM_COPY_UTIL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_DEV_FB_USED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "DCGM_FI_DEV_SM_CLOCK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_SM_CLOCK{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_DEV_MEM_CLOCK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_MEM_CLOCK{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  { "title": "XidError & Violations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "DCGM_FI_DEV_XID_ERRORS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  { "title": "Temperature & Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "DCGM_FI_DEV_GPU_TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_DEV_MEMORY_TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_MEMORY_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_DEV_POWER_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg by(gpu) (DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  { "title": "Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "DCGM_FI_PROF_GR_ENGINE_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_SM_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_SM_OCCUPANCY",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_OCCUPANCY{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_FP64_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP64_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_FP32_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP32_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_FP16_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP16_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_DRAM_ACTIVE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_DRAM_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PCIE_TX_BYTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "count(DCGM_FI_PROF_PCIE_TX_BYTES{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PCIE_TX_BYTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "count(DCGM_FI_PROF_PCIE_TX_BYTES{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_NVLINK_RX_BYTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "count(DCGM_FI_PROF_NVLINK_RX_BYTES{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_NVLINK_TX_BYTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "count(DCGM_FI_PROF_NVLINK_TX_BYTES{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  }
 ]
}