{
 "title": "LLM Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "GPU Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU占用比例",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  count(\n    avg_over_time(DCGM_FI_DEV_FB_USED[5m]) / (avg_over_time(DCGM_FI_DEV_FB_USED[5m]) + avg_over_time(DCGM_FI_DEV_FB_FREE[5m])) > 0.01\n  )\n) / \n(\n  count(DCGM_FI_DEV_FB_USED)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Cluster Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "GPU Utilization (cluster)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(DCGM_FI_DEV_GPU_UTIL[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization (Cluster)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(avg_over_time(DCGM_FI_DEV_FB_USED[5m])) / \n  (sum(avg_over_time(DCGM_FI_DEV_FB_USED[5m])) + sum(avg_over_time(DCGM_FI_DEV_FB_FREE[5m])))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "LLM Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "New Requests per Second (LLM Service)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_bytes_count[5m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Requests per Second (LLM Service)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_size_bytes_count{http_status_code=~\"2..\"}[5m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Time per Request (LLM Service)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[5m])) by (exported_job) / sum(rate(http_server_duration_milliseconds_count{}[5m])) by (exported_job) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "LLM Service Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Time to First Token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(rate(vllm:time_to_first_token_seconds_sum{}[5m]) / rate(vllm:time_to_first_token_seconds_count{}[5m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time per Generation Token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg(rate(vllm:time_per_output_token_seconds_sum{}[5m]) / rate(vllm:time_per_output_token_seconds_count{}[5m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Prompt Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "avg(avg_over_time(vllm:avg_prompt_throughput_toks_per_s[5m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Generation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "avg(avg_over_time(vllm:avg_generation_throughput_toks_per_s[5m])) by (exported_job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}