{
 "title": "Enova-LLM-Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prompt Throughput (Prefill phase)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(exported_job) (avg_prompt_throughput_tokens_per_second)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation throughput (Generation phase)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(exported_job) (avg_generation_throughput_tokens_per_second)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(exported_job) (http_server_active_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "running_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(exported_job) (running_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(exported_job) (pending_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU KV cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(exported_job) (gpu_kv_cache_usage_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM launch config",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "llm_engine_init_config", "legendFormat": "__auto" }
   ]
  }
 ]
}