# syntax=docker/dockerfile:1
FROM quay.io/ascend/vllm-ascend:v0.10.0rc1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        cmake \
        libnuma-dev \
        wget \
        git \
        net-tools \
        ocl-icd-libopencl1 \
        opencl-headers \
        clinfo \
        libpq5 && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements-docker.npu.txt /opt/enova/requirements.txt

RUN pip install build --no-cache-dir && \
    pip install pip setuptools setuptools_scm[toml]==8.3.1 toml poetry && \
    pip install -r /opt/enova/requirements.txt --no-cache-dir


COPY ./llmo /opt/enova/llmo

COPY ./scripts /opt/enova/scripts

RUN bash /opt/enova/scripts/pack_whl.llmo.sh 

ARG LLMO_VERSION=0.1.0
RUN pip install /opt/enova/llmo/enova-instrumentation-llmo/dist/enova_instrumentation_llmo-${LLMO_VERSION}-py3-none-any.whl --no-deps --no-cache-dir

ARG CACHEBUST=1

COPY . /opt/enova 

RUN cd /opt/enova && rm MANIFEST.in && bash ./scripts/pack_whl.enova.sh
ARG ENOVA_VERSION=0.1.0
RUN export TORCH_DEVICE_BACKEND_AUTOLOAD=0 && pip install -r /opt/enova/requirements.quant.txt --no-deps  --no-cache-dir && \
    pip install /opt/enova/dist/enova-${ENOVA_VERSION}-py3-none-any.whl --no-deps --no-cache-dir && \
    mkdir -p /workspace/model

