FROM nvcr.io/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        cmake \
        libnuma-dev \
        wget \
        git \
        net-tools \
        ocl-icd-libopencl1 \
        opencl-headers \
        clinfo \
        iputils-ping \
        vim \
        curl \
        build-essential \
        cmake \
        libibverbs-dev \
        libnuma-dev \
        libunwind-dev \
        libboost-all-dev \
        libssl-dev \
        pybind11-dev \
        pkg-config \
        patchelf

COPY ./requirements-docker.txt /opt/enova/requirements.txt

RUN cd /tmp && \
    curl -O https://repo.anaconda.com/miniconda/Miniconda3-py312_25.9.1-3-Linux-x86_64.sh && \
    bash /tmp/Miniconda3-py312_25.9.1-3-Linux-x86_64.sh -b && \
    rm /tmp/Miniconda3-py312_25.9.1-3-Linux-x86_64.sh && \
    echo "export PATH=$HOME/miniconda3/bin:$PATH" >> ~/.bashrc
ENV PATH="/root/miniconda3/bin:${PATH}"

RUN pip install build --no-cache-dir && \
    pip install pip setuptools setuptools_scm[toml]==8.3.1 toml poetry && \\
    pip install -r /opt/enova/requirements.txt --no-cache-dir

ARG CACHEBUST=1

COPY . /opt/enova

RUN cd /opt/enova && bash ./scripts/pack_whl.enova.sh
ARG ENOVA_VERSION=0.1.1

RUN pip install -r /opt/enova/requirements.quant.txt --no-cache-dir && \
    pip install /opt/enova/dist/enova-${ENOVA_VERSION}-py3-none-any.whl --no-deps --no-cache-dir && \
    mkdir -p /workspace
WORKDIR /workspace
