# image enova:base
FROM nvcr.io/nvidia/pytorch:24.07-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        cmake \
        libnuma-dev \
        wget \
        git \
        net-tools \
        ocl-icd-libopencl1 \
        opencl-headers \
        clinfo && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements-docker.npu.txt /opt/enova/requirements.txt

RUN pip install build --no-cache-dir && \
    pip install pip setuptools setuptools_scm[toml]==8.3.1 toml poetry && \
    pip install -r /opt/enova/requirements.txt --no-cache-dir

