# syntax=docker/dockerfile:1
FROM hiyouga/llamafactory:0.9.4-npu-a2

ENV DEBIAN_FRONTEND=noninteractive

RUN bash -c "echo -e 'deb http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse \n \
deb-src http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse \n \
deb http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse \n \
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse \n \
deb http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse \n \
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse \n \
deb http://mirrors.aliyun.com/ubuntu/ jammy-proposed main restricted universe multiverse \n \
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-proposed main restricted universe multiverse \n \
deb http://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse \n \
deb-src http://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse \n '" > /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        cmake \
        libnuma-dev \
        wget \
        git \
        net-tools \
        ocl-icd-libopencl1 \
        opencl-headers \
        clinfo \
        libpq5 && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements-docker.npu.txt /opt/enova/requirements.txt

RUN pip install build --no-cache-dir && \
    pip install pip setuptools setuptools_scm[toml]==8.3.1 toml poetry && \
    pip install -r /opt/enova/requirements.txt --no-cache-dir


COPY ./llmo /opt/enova/llmo

COPY ./scripts /opt/enova/scripts

RUN bash /opt/enova/scripts/pack_whl.llmo.sh 

ARG LLMO_VERSION=0.1.0
RUN pip install /opt/enova/llmo/enova-instrumentation-llmo/dist/enova_instrumentation_llmo-${LLMO_VERSION}-py3-none-any.whl --no-deps --no-cache-dir

ARG CACHEBUST=1

RUN apt update && apt install -y mpich libmpich-dev build-essential gfortran

COPY . /opt/enova 

RUN cd /opt/enova && rm MANIFEST.in && bash ./scripts/pack_whl.enova.sh
ARG ENOVA_VERSION=0.1.0
RUN apt install -y vim && export TORCH_DEVICE_BACKEND_AUTOLOAD=0 && pip install -r /opt/enova/requirements.train.txt --no-deps  --no-cache-dir && \
    pip install /opt/enova/dist/enova-${ENOVA_VERSION}-py3-none-any.whl --no-deps --no-cache-dir && \
    mkdir -p /workspace/model
