# syntax=docker/dockerfile:1
# hiyouga/llamafactory:0.9.4-npu-a2
FROM quay.io/ascend/llamafactory:0.9.4-npu-a2

ENV DEBIAN_FRONTEND=noninteractive

# RUN sed -i 's/http:\/\/ports.ubuntu.com\/ubuntu-ports/http:\/\/mirrors.tuna.tsinghua.edu.cn\/ubuntu/g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        g++ \
        cmake \
        libnuma-dev \
        wget \
        git \
        net-tools \
        ocl-icd-libopencl1 \
        opencl-headers \
        clinfo \
        libpq5 \
        ninja-build \
        mpich libmpich-dev build-essential gfortran vim

COPY ./requirements-docker.npu.txt /opt/enova/requirements.txt

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && pip install build --no-cache-dir && \
    pip install pip setuptools setuptools_scm[toml]==8.3.1 toml poetry && \
    pip install -r /opt/enova/requirements.txt --no-cache-dir


COPY ./llmo /opt/enova/llmo

COPY ./scripts /opt/enova/scripts

RUN bash /opt/enova/scripts/pack_whl.llmo.sh 

ARG LLMO_VERSION=0.1.0
RUN pip install /opt/enova/llmo/enova-instrumentation-llmo/dist/enova_instrumentation_llmo-${LLMO_VERSION}-py3-none-any.whl --no-deps --no-cache-dir

ARG CACHEBUST=1

COPY . /opt/enova 

RUN cd /opt/enova && rm MANIFEST.in && bash ./scripts/pack_whl.enova.sh
ARG ENOVA_VERSION=0.1.0
RUN export TORCH_DEVICE_BACKEND_AUTOLOAD=0 && pip install -r /opt/enova/requirements.train.npu.txt --no-deps  --no-cache-dir && \
    pip install /opt/enova/dist/enova-${ENOVA_VERSION}-py3-none-any.whl deepspeed==0.16.0 --no-deps --no-cache-dir && \
    mkdir -p /workspace/model
