ARG HARBOR_PATH=emergingai

FROM ${HARBOR_PATH}/python:base

RUN apt-get install -y \
    ocl-icd-libopencl1 \
    opencl-headers \
    clinfo

RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

COPY ./dist/enova-0.0.3-py3-none-any.whl .
COPY ./llmo/enova-instrumentation-llmo/dist/enova_instrumentation_llmo-0.0.3-py3-none-any.whl .

RUN pip install enova_instrumentation_llmo-0.0.3-py3-none-any.whl enova-0.0.3-py3-none-any.whl 

RUN pip install vllm