version: "3.8"

services:
  traffic_injector:
    image: 60.204.135.2/emergingai/enova-jmeter:v0.0.2
    command:
      - sh
      - -c
      - |
        rm -rf /data/report
        mkdir /data/report
        jmeter -n -t /data/jmeter-config.xml -l /data/report/report.log -e -o /data/report
    volumes:
      - ${DATA_FILE}:/opt/data.csv
      - ${OUTPUT}:/data
    networks:
      - enova-net

volumes:
  output:

networks:
  enova-net:
    enable_ipv6: false
